/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BusinessInfo = IDL.Record({
  'instagram' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Category = IDL.Variant({ 'addOn' : IDL.Null, 'main' : IDL.Null });
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BusinessInfo = IDL.Record({
    'instagram' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Category = IDL.Variant({ 'addOn' : IDL.Null, 'main' : IDL.Null });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };